from .alamut import Alamut
from .franklin import Franklin
from .clinvar import ClinVar
from .lovd import LOVD
from .cosmic import COSMIC
from .dbsnp import dbSNP
from .alamut import Alamut
from .cbioportal import cBioPortal
from .ckb import CKB
from .oncokb import OncoKB
from .pmkb import PMKB
from .tp53 import TP53
from .varsome import Varsome
from .hmf import HMF
from .mutalyzer import Mutalyzer
from .clingen import Clingen