from .alamut import Alamut
from .franklin import Franklin
from .clinvar import Clinvar
from .lovd import Lovd
from .cosmic import Cosmic
from .dbsnp import dbSNP
from .alamut import Alamut
from .cbioportal import CBioPortal
from .ckb import CKB
from .oncokb import OncoKB
from .pmkb import PMKB
from .tp53 import TP53