name: molclass
channels:
    - conda-forge
dependencies:
    - python=3.13
    - pip
    - gcc_linux-64
    - gxx_linux-64
    - nodejs=22
    - typescript=5.9.3
    - pip:
          - -r requirements.txt
